version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-flake8
jobs:
  test-flake8:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: sudo pip install flake8
      - run: flake8